from ubuntu:18.04

run apt-get -y update
run apt-get -y install vim
run apt-get -y install iputils-ping
run apt-get -y install net-tools
run apt-get -y install curl
run apt-get -y install openjdk-11-jdk
run apt-get -y install git
run apt-get -y install subversion
run apt-get -y install mc
run apt-get -y install wget
run apt-get -y install screen
run apt-get -y install maven
run apt-get -y install libstdc++5
run apt-get -y install software-properties-common

ENV JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
