from ubuntu

run						\
		apt-get -y update		\
	&&      apt-get -y install vim		\
	&&	apt-get -y install iputils-ping	\
	&&      apt-get -y install net-tools	\
	&&	apt-get -y install curl		\
	&&	apt-get -y install default-jdk	\
	&&      apt-get -y install git		\
	&&      apt-get -y install maven
